query CountryDetail($code: ID!) {
  country(code: $code) {
    code
    name
    native
    phone
    emoji
    capital
    currency
    continent {
      code
      name
    }
    languages {
      code
      name
      native
    }
    states {
      code
      name
    }
  }
}
